version: '3.1'

services:
  nginx:
    image: nginx
    restart: always
    hostname: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/cert:/etc/nginx/cert
    environment:
      - TZ=Asia/Shanghai