version: '3.1'

services:
  nginx:
    image: nginx
    restart: always
    hostname: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./cert:/etc/nginx/cert
      - ./html:/usr/share/nginx/html
    environment:
      - TZ=Asia/Shanghai