version: '3'

services:
  nginx:
    image: nginx
    restart: always
    hostname: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./cert:/etc/nginx/cert:ro
      - ./html:/usr/share/nginx/html
      - ./log:/log