version: '3.1'

services:
  nginx:
    image: nginx
    restart: always
    hostname: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${HOME}/appdata/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${HOME}/appdata/nginx/conf.d:/etc/nginx/conf.d
      - ${HOME}/appdata/nginx/cert:/etc/nginx/cert
      - ${HOME}/appdata/nginx/html:/usr/share/nginx/html
      - ${HOME}/appdata/nginx/log:/var/log/nginx
    environment:
      - TZ=Asia/Shanghai